using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Windows.Forms;

namespace PSQueue
{
    public class GVar
    {
        internal static string gvPermitApprove;
        internal static string gvPermitCancel;
        internal static string gvPermitDel;
        internal static string gvPermitEdit;
        internal static string gvPermitEntry;
        internal static string gvPermitNew;
        internal static string gvPermitPrint;
        internal static string gvUserType;
        internal static string gvFirstUrl;
        internal static string gvKet;
        internal static string gvSCode = "";
        internal static string gvDocNo;
        internal static string gvDocS;
        internal static string gvSName;
        internal static string gvDate;
        internal static string gvMonth;
        internal static string gvYear;
        internal static string gvName;
        internal static string gvQuota;
        internal static string gvQNo;
        internal static string gvCarNum;
        internal static string gvFront;
        internal static string gvCaneS;
        internal static string gvCaneNo;
        internal static string gvDocE;
        internal static int gvRow;
        internal static string gvCCS;
        internal static string gvWeightF;
        internal static string gvPriceF;
        internal static string gvDueS;
        internal static string gvDueE;
        internal static string gvCarNumChk;
        internal static string gvUser;
        internal static string gvDateBill;
        internal static string gvSp;
        internal static int gvRowIndex;
        internal static string gvLogData;
        internal static string gvLockDue;
        internal static int gvCount;
        internal static double gvTotalWeight;
        internal static string gvKeepTakao;
        internal static string gvEmpID;
        internal static string gvStation;
        internal static bool gvOnline;
        internal static string gvServerIP;
        internal static string gvConnectionDB;
        internal static string gvINOUT;
        internal static string gvTypeProgram;
        internal static string gvDataCount;
        internal static string gvDataSum;
        internal static string gvCaneType;
        internal static string gvComport;
        internal static string gvPrintMode;
        internal static string gvBillingOld;
        internal static string gvStationSelect;
        internal static string gvTKNoOld;
        internal static string gvSampleNoOld;
        internal static string gvPrintAgain;
        internal static int gvCountOFFLINE;
        internal static bool gvNewBill;
        internal static bool gvTKNew;
        internal static bool gvChangeBill;
        internal static string gvQLockOnOff;
        internal static string gvDBConnect;
        internal static string gvStatusFail;
        internal static bool gvESC;
        internal static string gvLockBar;
        internal static string gvPrintQLock;
        internal static string gvLockAlert;
        internal static string gvSourcePath;
        internal static string gvDesPath;
        internal static string gvTypeDocTakao;
        internal static bool gvCarryPriceStatus;
        internal static string gvDBName;
        internal static string gvSubQuota;
        internal static string gvBillS;
        internal static string gvBillE;
        internal static string gvCutcarNo;
        internal static string gvCovidsound;
        internal static bool gvAddCarnum2 = false;
        internal static string gvModeSearchRm = "";
        internal static string gvCarcutRm = "";
        internal static string gvCartruckRm = "";
        internal static string gvCarkeepRm = "";
        internal static string gvAllRm = "";
        internal static string gvCarSearchRm = "";
        internal static string gvQuotaMom = "";
        internal static string gvCanetypeMom = "";
        internal static bool gvStatusCancel = false;
        internal static string gvBonsucroStatus = "";
    }
}